#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
n="Best School"
i="0"

until [ $i -eq 10 ]; do
if [ $i -eq 8 ]; then
echo "$n"
echo "Hi"
else
echo "$n"
((i++))
    sleep 1  # Add a 1-second delay
done
